import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'

const Setting: NextPage<any> = ({ state }) => {
  return (
    <div className=''>
      <Head>
        <title>Setting page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>HomeとSettingでcontextが共有される</div>
      <div>{state?.user ? state.user.email : ''}</div>

      <h1 className=''>
        Setting Page
      </h1>
    </div>
  )
}

export default Setting
